; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
lib_deps = TFT_eSPI
build_flags = 
    -D LOAD_GLCD=1   
    -D LOAD_FONT2=1
;    -D LOAD_FONT4=1
;    -D LOAD_FONT6=1
;    -D LOAD_FONT7=1
    -D LOAD_FONT8N=1
;    -D LOAD_GFXFF=1

[env:CYD-ESP32-ST7789]
board = esp32dev
build_flags = 
    ${env.build_flags}
    -D ST7789_DRIVER=1
    -D USER_SETUP_LOADED=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D TOUCH_CS=33       
    -D SPI_TOUCH_FREQUENCY=2500000
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_INVERSION_OFF=1
    -D SPI_FREQUENCY=80000000

[env:CYD-ESP32-ILI9341]
board = esp32dev
build_flags = 
    ${env.build_flags}
    -D ILI9341_DRIVER=1 
    -D USER_SETUP_LOADED=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D TOUCH_CS=33
    -D SPI_TOUCH_FREQUENCY=2500000    
    -D SPI_FREQUENCY=40000000

[env:FREENOVE-FNK0104]
; ARGH! This is not working, and I do not yet know why. The same TFT_eSPI definitions work in Arduino IDE, but not here. I need to work out what the issue is! 
; Is it the board definition? Is it the build flags? Is it something else? 

board = freenove_esp32_s3_wroom

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

build_flags =     
    ${env.build_flags}
    -D USER_SETUP_LOADED=1
    -D ILI9341_2_DRIVER=1 
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_INVERSION_ON=1
    -D TFT_BL=45
    -D TFT_BACKLIGHT_ON=HIGH
    -D TFT_MISO=13
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=46
    -D TFT_RST=-1
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=6000000
    -D SPI_TOUCH_FREQUENCY=2500000
